# Generated by Django 4.0.2 on 2022-02-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra_rpg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='armors',
            field=models.ManyToManyField(to='gra_rpg_app.Armor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weapons',
            field=models.ManyToManyField(to='gra_rpg_app.Weapon'),
        ),
    ]
