# Generated by Django 4.0.2 on 2022-02-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra_rpg_app', '0006_enemyhealth_delete_enemyfight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnemyHealth',
        ),
        migrations.AddField(
            model_name='profile',
            name='enemy_health',
            field=models.IntegerField(default=0),
        ),
    ]
